export const SECTION_IDS = [
  "button",
  "badge",
  "chip",
  "alert",
  "tooltip",
  "popover",
  "avatar",
  "switch",
  "checkbox",
  "textfield",
  "link",
  "progressbar",
  "separator",
  "radiogroup",
  "profilecard",
  "eventcard",
  "calendarcard",
  "conversation",
  "timelineitem",
  "dialog",
  "createbutton-hook",
  "createcheckboxgroup-hook",
  "listbox",
  "menu",
  "select",
  "styled-select",
  "styled-menu",
  "styled-listbox",
  "styled-tabs",
  "styled-breadcrumbs",
  "styled-numberfield",
  "styled-searchfield",
  "styled-slider",
  "styled-combobox",
  "actiongroup",
  "toolbar",
  "actionbar",
  "disclosure",
  "meter",
  "taggroup",
  "calendar",
  "datepicker",
  "toast",
  "dropzone",
  "filetrigger",
  "table",
  "gridlist",
  "tree",
  "rangecalendar",
  "datefield",
  "timefield",
  "colorslider",
  "colorarea",
  "colorwheel",
  "colorfield",
  "colorswatch",
  "textarea",
  "daterangepicker",
  "colorswatchpicker",
  "coloreditor",
  "contextualhelp",
  "rangeslider",
  "alertdialog",
  "actionmenu",
  "flex",
  "grid",
  "theme",
] as const;

export type SectionId = (typeof SECTION_IDS)[number];

export const SECTION_NAMES: Record<SectionId, string> = {
  button: "Button",
  badge: "Badge",
  chip: "Chip",
  alert: "Alert",
  tooltip: "Tooltip",
  popover: "Popover",
  avatar: "Avatar",
  switch: "Switch",
  checkbox: "Checkbox",
  textfield: "Text Field",
  link: "Link",
  progressbar: "Progress Bar",
  separator: "Separator",
  radiogroup: "Radio Group",
  profilecard: "Profile Card",
  eventcard: "Event Card",
  calendarcard: "Calendar Card",
  conversation: "Conversation",
  timelineitem: "Timeline Item",
  dialog: "Dialog",
  "createbutton-hook": "createButton Hook",
  "createcheckboxgroup-hook": "createCheckboxGroup Hook",
  listbox: "ListBox",
  menu: "Menu",
  select: "Select",
  "styled-select": "Styled Select",
  "styled-menu": "Styled Menu",
  "styled-listbox": "Styled ListBox",
  "styled-tabs": "Styled Tabs",
  "styled-breadcrumbs": "Styled Breadcrumbs",
  "styled-numberfield": "Number Field",
  "styled-searchfield": "Search Field",
  "styled-slider": "Slider",
  "styled-combobox": "ComboBox",
  actiongroup: "Action Group",
  toolbar: "Toolbar",
  actionbar: "Action Bar",
  disclosure: "Disclosure",
  meter: "Meter",
  taggroup: "Tag Group",
  calendar: "Calendar",
  datepicker: "Date Picker",
  toast: "Toast",
  dropzone: "DropZone",
  filetrigger: "FileTrigger",
  table: "Table",
  gridlist: "GridList",
  tree: "Tree",
  rangecalendar: "Range Calendar",
  datefield: "Date Field",
  timefield: "Time Field",
  colorslider: "Color Slider",
  colorarea: "Color Area",
  colorwheel: "Color Wheel",
  colorfield: "Color Field",
  colorswatch: "Color Swatch",
  textarea: "TextArea",
  daterangepicker: "Date Range Picker",
  colorswatchpicker: "Color Swatch Picker",
  coloreditor: "Color Editor",
  contextualhelp: "Contextual Help",
  rangeslider: "Range Slider",
  alertdialog: "Alert Dialog",
  actionmenu: "Action Menu",
  flex: "Flex Layout",
  grid: "Grid Layout",
  theme: "Theme / Provider",
};
