/**
 * Event utilities for detecting virtual clicks and event handling.
 * Based on @react-aria/utils event utilities.
 */
/**
 * Checks if a click event was generated from a virtual source like a screen reader.
 * Virtual clicks typically have detail of 0 and may have zero coordinates.
 */
export declare function isVirtualClick(event: MouseEvent | PointerEvent): boolean;
/**
 * Checks if a pointer event was generated by a virtual source.
 * iOS VoiceOver fires pointer events with incorrect coordinates.
 * These events have zero width/height.
 */
export declare function isVirtualPointerEvent(event: PointerEvent): boolean;
/**
 * Creates a synthetic mouse event for programmatic clicking.
 */
export declare function createMouseEvent(type: string, nativeEvent?: Event): MouseEvent;
/**
 * Creates a chain of event handlers that calls each in sequence.
 */
export declare function chain<T extends (...args: any[]) => any>(...callbacks: (T | undefined | null)[]): T;
/**
 * Sets the target property on an event object.
 * Used for synthetic events where target needs to be modified.
 */
export declare function setEventTarget<T extends Event>(event: T, target: EventTarget): void;
//# sourceMappingURL=events.d.ts.map