/**
 * Event utilities for detecting virtual clicks and event handling.
 * Based on @react-aria/utils event utilities.
 */

import { isAndroid } from './platform';

/**
 * Checks if a click event was generated from a virtual source like a screen reader.
 * Virtual clicks typically have detail of 0 and may have zero coordinates.
 */
export function isVirtualClick(event: MouseEvent | PointerEvent): boolean {
  // JAWS/NVDA with Firefox.
  if ((event as PointerEvent).pointerType === '' && event.isTrusted) {
    return true;
  }

  // Android TalkBack's detail value varies depending on the event listener providing the event.
  // If pointerType is defined, event is from a click listener.
  if (isAndroid() && (event as PointerEvent).pointerType) {
    return event.type === 'click' && (event as MouseEvent).buttons === 1;
  }

  return event.detail === 0 && !(event as PointerEvent).pointerType;
}

/**
 * Checks if a pointer event was generated by a virtual source.
 * iOS VoiceOver fires pointer events with incorrect coordinates.
 * These events have zero width/height.
 */
export function isVirtualPointerEvent(event: PointerEvent): boolean {
  // If the pointer size is zero, then we assume it's from a screen reader.
  // Android TalkBack double tap will sometimes return a event with width and height of 1
  // and pointerType === 'mouse' so we need to check for a specific combination of event attributes.
  // Cannot use "event.pressure === 0" as the sole check due to Safari pointer events always returning pressure === 0.
  return (
    (!isAndroid() && event.width === 0 && event.height === 0) ||
    (event.width === 1 &&
      event.height === 1 &&
      event.pressure === 0 &&
      event.detail === 0 &&
      event.pointerType === 'mouse')
  );
}

/**
 * Creates a synthetic mouse event for programmatic clicking.
 */
export function createMouseEvent(type: string, nativeEvent?: Event): MouseEvent {
  const init: MouseEventInit = {
    bubbles: true,
    cancelable: true,
    view: window,
  };

  // Copy properties from the native event if provided
  if (nativeEvent) {
    const e = nativeEvent as MouseEvent;
    init.screenX = e.screenX;
    init.screenY = e.screenY;
    init.clientX = e.clientX;
    init.clientY = e.clientY;
    init.ctrlKey = e.ctrlKey;
    init.shiftKey = e.shiftKey;
    init.altKey = e.altKey;
    init.metaKey = e.metaKey;
    init.button = e.button;
    init.buttons = e.buttons;
    init.relatedTarget = e.relatedTarget;
  }

  return new MouseEvent(type, init);
}

/**
 * Creates a chain of event handlers that calls each in sequence.
 */
export function chain<T extends (...args: any[]) => any>(
  ...callbacks: (T | undefined | null)[]
): T {
  return ((...args: Parameters<T>) => {
    for (const callback of callbacks) {
      if (typeof callback === 'function') {
        callback(...args);
      }
    }
  }) as T;
}

/**
 * Sets the target property on an event object.
 * Used for synthetic events where target needs to be modified.
 */
export function setEventTarget<T extends Event>(event: T, target: EventTarget): void {
  Object.defineProperty(event, 'target', {
    value: target,
    writable: false,
    configurable: true,
  });
  Object.defineProperty(event, 'currentTarget', {
    value: target,
    writable: false,
    configurable: true,
  });
}
