/**
 * Event utilities for detecting virtual clicks and event handling.
 * Based on @react-aria/utils event utilities.
 */

/**
 * Checks if a click event was generated from a virtual source like a screen reader.
 * Virtual clicks typically have detail of 0 and may have zero coordinates.
 */
export function isVirtualClick(event: MouseEvent | PointerEvent): boolean {
  // The detail property is 0 for non-mouse clicks (keyboard, screen reader)
  // However, we need to be careful about actual clicks at (0,0) or events
  // that have been re-dispatched
  if ((event as any).mozInputSource === 0 && event.isTrusted) {
    // Firefox bug: clicks from screen readers have mozInputSource = 0
    return true;
  }

  // Android TalkBack fires click events with detail=1 but offsetX/offsetY = 0
  if (isAndroidTalkBackClick(event)) {
    return true;
  }

  // Screen readers on Safari/Chrome have detail = 0
  return event.detail === 0 && !(event as PointerEvent).pointerType;
}

/**
 * Detects Android TalkBack clicks which have detail=1 but zero offsets.
 */
function isAndroidTalkBackClick(event: MouseEvent | PointerEvent): boolean {
  // TalkBack on Android sends click events with detail=1 but offsetX/Y = 0
  return (
    event.detail === 1 &&
    (event as MouseEvent).offsetX === 0 &&
    (event as MouseEvent).offsetY === 0
  );
}

/**
 * Checks if a pointer event was generated by a virtual source.
 * iOS VoiceOver fires pointer events with incorrect coordinates.
 * These events have zero width/height.
 */
export function isVirtualPointerEvent(event: PointerEvent): boolean {
  // Virtual events typically have no dimensions
  // iOS VoiceOver fires pointer events with width=0, height=0
  return (
    (event.width === 0 && event.height === 0) ||
    // Some screen readers send events with pointerType but no actual pointer
    (event.pointerType === 'mouse' &&
      event.width === 1 &&
      event.height === 1 &&
      event.pressure === 0 &&
      event.detail === 0 &&
      event.buttons === 0)
  );
}

/**
 * Creates a synthetic mouse event for programmatic clicking.
 */
export function createMouseEvent(type: string, nativeEvent?: Event): MouseEvent {
  const init: MouseEventInit = {
    bubbles: true,
    cancelable: true,
    view: window,
  };

  // Copy properties from the native event if provided
  if (nativeEvent) {
    const e = nativeEvent as MouseEvent;
    init.screenX = e.screenX;
    init.screenY = e.screenY;
    init.clientX = e.clientX;
    init.clientY = e.clientY;
    init.ctrlKey = e.ctrlKey;
    init.shiftKey = e.shiftKey;
    init.altKey = e.altKey;
    init.metaKey = e.metaKey;
    init.button = e.button;
    init.buttons = e.buttons;
    init.relatedTarget = e.relatedTarget;
  }

  return new MouseEvent(type, init);
}

/**
 * Creates a chain of event handlers that calls each in sequence.
 */
export function chain<T extends (...args: any[]) => any>(
  ...callbacks: (T | undefined | null)[]
): T {
  return ((...args: Parameters<T>) => {
    for (const callback of callbacks) {
      if (typeof callback === 'function') {
        callback(...args);
      }
    }
  }) as T;
}

/**
 * Sets the target property on an event object.
 * Used for synthetic events where target needs to be modified.
 */
export function setEventTarget<T extends Event>(event: T, target: EventTarget): void {
  Object.defineProperty(event, 'target', {
    value: target,
    writable: false,
    configurable: true,
  });
  Object.defineProperty(event, 'currentTarget', {
    value: target,
    writable: false,
    configurable: true,
  });
}
